version: '3'

services:
#  mysql:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
  postgres:
    image: "postgres:9.6" # use latest official postgres version
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      #- POSTGRES_DB=servian
      #env_file:
      #- database.env # configure postgres
#    volumes:
#    - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  servian:
    #image: servian/techchallengeapp:latest
    image: servian
    container_name: servian
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
    - KEY="VAL"
#volumes:
#  database-data: # named volumes can be managed easier using docker-compose

